version: '3'

dotenv: ['.env']

tasks:
  schema:
    cmds:
      - go run cmd/schema/main.go
  idl:
    vars:
      OUT_DIR: pkg/idlpb
    cmds:
      - mkdir -p {{.OUT_DIR}}
      - protoc -I ./idl --go_opt=paths=source_relative --go_out={{.OUT_DIR}} ./idl/**/*.proto
